/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f401rb.h"
#include "stm32f401rb_gpio_driver.h"



void delay(){
	for(int i=0; i< 5000 ;i ++);
}

int main(void)
{

	gpio_handle_t led;
	gpio_handle_t button;

	led.pGPIOx = GPIOA;
	led.pconfig.GPIO_pinNumber = GPIO_PIN_NO5;
	led.pconfig.GPIO_pinMode = GPIO_MODE_OUTPUT ;
	led.pconfig.GPIO_pinOptype = GPIO_PUSH_PULL;
	led.pconfig.GPIO_pinSpeed = GPIO_SPEED_HIGH;

	GPIOA_PCLK_EN();
	GPIO_init(&led);


	button.pGPIOx = GPIOC;
	button.pconfig.GPIO_pinNumber = GPIO_PIN_NO13;
	button.pconfig.GPIO_pinMode = GPIO_MODE_INPUT ;
	button.pconfig.GPIO_pinOptype = GPIO_PUSH_PULL;
	button.pconfig.GPIO_pinSpeed = GPIO_SPEED_HIGH;
	button.pconfig.GPIO_pinPupdcontrol = GPIO_PULL_NONE;

	GPIOC_PCLK_EN();
	GPIO_init(&button);
	//GPIO_write_pin(GPIOA,GPIO_PIN_NO5,0);

    /* Loop forever */
	for(;;){

		if(!GPIO_read_pin(GPIOC,GPIO_PIN_NO13)){

			GPIO_toggle_pin(GPIOA,GPIO_PIN_NO5);

		}
	}
}
